import streamlit as st
import requests
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO
from navbar import show_navbar

API_URL = "http://127.0.0.1:8000"

st.set_page_config(page_title="PDF Reports", page_icon="📄", layout="wide")
show_navbar()
st.markdown("""
<style>
[data-testid="stSidebar"] {
    display: none;
}
[data-testid="collapsedControl"] {
    display: none;
}
</style>
""", unsafe_allow_html=True)

st.title("📄 PDF Report Generator")

students = requests.get(f"{API_URL}/students/all").json().get("students", [])
marks = requests.get(f"{API_URL}/marks/all").json().get("marks", [])

reg_numbers = [s["register_number"] for s in students]

selected = st.selectbox("Select Student Register Number", reg_numbers)

student = next((s for s in students if s["register_number"] == selected), None)
mark = next((m for m in marks if m["register_number"] == selected), None)

def generate_pdf(student, mark):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    width, height = A4

    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(50, height - 60, "Student Performance Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 100, f"Name: {student['name']}")
    pdf.drawString(50, height - 120, f"Register Number: {student['register_number']}")
    pdf.drawString(50, height - 140, f"Department: {student['department']}")
    pdf.drawString(50, height - 160, f"Year: {student['year']}")
    pdf.drawString(50, height - 180, f"Semester: {student['semester']}")

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 220, "Performance Summary")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 250, f"Total Marks: {mark['total']}")
    pdf.drawString(50, height - 270, f"Average: {mark['average']}%")
    pdf.drawString(50, height - 290, f"Grade: {mark['grade']}")
    pdf.drawString(50, height - 310, f"Risk Level: {mark['risk_level']}")

    y = height - 350
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Subject Marks")

    y -= 30
    pdf.setFont("Helvetica", 12)

    for subject, score in mark["subjects"].items():
        pdf.drawString(70, y, f"{subject}: {score}")
        y -= 20

    y -= 20
    pdf.drawString(50, y, "Weak Subjects: " + (", ".join(mark["weak_subjects"]) if mark["weak_subjects"] else "None"))

    y -= 25
    pdf.drawString(50, y, "Strong Subjects: " + (", ".join(mark["strong_subjects"]) if mark["strong_subjects"] else "None"))

    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawString(50, 40, "Generated by Student Performance Analysis Dashboard")

    pdf.save()
    buffer.seek(0)
    return buffer

if student and mark:
    st.success("Student report is ready.")

    st.write(f"Name: {student['name']}")
    st.write(f"Average: {mark['average']}%")
    st.write(f"Grade: {mark['grade']}")

    pdf_file = generate_pdf(student, mark)

    st.download_button(
        label="⬇️ Download PDF Report",
        data=pdf_file,
        file_name=f"{student['register_number']}_performance_report.pdf",
        mime="application/pdf"
    )
else:
    st.warning("Marks not found for this student.")